NAME_MIN_LENGTH = 2
NAME_MAX_LENGTH = 128
DESCRIPTION_MAX_LENGTH = 512

USERNAME_MIN_LENGTH = 3
USERNAME_MAX_LENGTH = 64

FILE_PATH_MAX_LENGTH = 512

# STORAGE
PROJECT_IMAGE_BUCKET_NAME = "project-image"
SONG_FILES_BUCKET_NAME = "song-files"
